"use strict";
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const percent=v=>(Number(v)*100).toFixed(4).replace(/0+$/," ").trim().replace(/\.$/,"")+"%";
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
$("location").innerHTML=Object.values(LOCATIONS).map(l=>`<option value="${esc(l.id)}">Lv ${l.recommendedLevel} · ${esc(l.name)}</option>`).join("");
function chooseLocation(){const l=LOCATIONS[$("location").value];$("enemy").innerHTML=l.enemyIds.map(id=>ENEMIES[id]).filter(Boolean).map(e=>`<option value="${esc(e.id)}">Lv ${e.level} · ${esc(e.name)}</option>`).join("");renderAtlas();}
function renderAtlas(){const e=ENEMIES[$("enemy").value];if(!e)return;const pool=e.dropPool.map(findTemplateById).filter(Boolean),profile=PROGRESSION_ECONOMY.equipmentQualityProfiles[e.equipmentQualityProfile]??PROGRESSION_ECONOMY.equipmentQualityProfiles.start;
$("summary").innerHTML=`<div class="metrics"><span>${esc(e.name)} · Lv ${e.level}</span><span>HP ${e.maxHp}</span><span>Damage ${e.minDamage}–${e.maxDamage}</span><span>Defense ${e.defense}</span><span>XP ${e.xp} / Gold ${e.gold}</span><span>Equipment ${percent(e.dropChance)}</span></div>`;
$("rewards").innerHTML=table(["Material","Per-kill chance","Amount","Quality, conditional on drop"],(e.materialDrops??[]).map(d=>{const m=MATERIALS[d.templateId],q=PROGRESSION_ECONOMY.materialQualityProfiles[d.qualityProfile];return [`<img src="${esc(m.asset)}" alt="">${esc(m.name)}`,percent(d.chance),esc((d.quantity??[1,1]).join("–")),q?Object.entries(q).map(([k,v])=>esc(k)+" "+percent(v)).join(" · "):esc(d.quality??"common")];}));
$("items").innerHTML=`<p>${Object.entries(profile).map(([k,v])=>esc(k)+" "+percent(v)).join(" · ")}</p>`+table(["Template","Slot / Tier","Per-kill chance","Forge: gold & inputs"],pool.filter(t=>t.name.toLowerCase().includes($("search").value.toLowerCase())).map(t=>{const r=FORGE_RECIPES.find(r=>r.templateId===t.icon);return [`<img src="${esc(t.image??"assets/placeholders/weapon.svg")}" alt="">${esc(t.name)}<br><small>${esc(t.icon)}</small>`,esc(t.slot)+" / "+(t.itemTier??e.itemTier??1),percent(e.dropChance/pool.length),r?`${r.gold} gold · Lv ${r.requiredLevel??1}<br>`+r.materials.map(m=>`<img src="${esc(MATERIALS[m.id]?.asset)}" alt="">${esc(MATERIALS[m.id]?.name)} ×${m.qty}`).join("<br>"):"No recipe"]; }));
const affixProbabilities=content100AffixProbabilities(e);
$("affixes").innerHTML=table(["Name / type","Internal tier / weight","Compatible templates","Per-kill chance (base)","Rolled stats"],Object.values(AFFIXES).filter(a=>e.affixTierPool?.[a.tier]>0&&pool.some(t=>content100AffixEligible(a,e,t))).map(a=>[esc(a.displayName)+" / "+a.type,`T${a.tier} · ${content100AffixWeight(a).toFixed(2)} · tier weight ${e.affixTierPool[a.tier]}`,pool.filter(t=>content100AffixEligible(a,e,t)).length+" / "+pool.length,percent(affixProbabilities[a.id]??0),[...a.modifiers,...a.drawbacks].map(m=>`${esc(STATS[m.statId].displayName)} ${m.minValue}–${m.maxValue}`).join("<br>")]));
$("sets").innerHTML=Object.values(CONTENT_100.sets).map(s=>`<details><summary>${esc(s.name)} · item tier ${s.tier} · 7 pieces</summary>${s.bonuses.map(b=>`<p>${b.pieces} pieces: ${esc(JSON.stringify(b.stats))}</p>`).join("")}</details>`).join("");
}
$("progression").innerHTML=table(["Levels","Location","Normal HP / boss HP","Gold per kill (normal / boss)","Craft base gold"],CONTENT_100.locations.map(l=>{const t=l.itemTier,n=CONTENT_100.enemies[`c100-t${t}-e1`],b=CONTENT_100.enemies[`c100-t${t}-e4`];return [`${l.recommendedLevel}–${l.maxLevel}`,esc(l.name),n.maxHp+" / "+b.maxHp,n.gold+" / "+b.gold,CONTENT_100.recipes.find(r=>r.tier===t).gold];}));
$("location").addEventListener("change",chooseLocation);$("enemy").addEventListener("change",renderAtlas);$("search").addEventListener("input",renderAtlas);chooseLocation();
